#!/bin/bash

#iptables_report="iptables-save \|grep -v '\(virbr0\)\|\(^:\)\|\(^#\)\|\(^COMMIT$\)'"

function state_report {
	echo "### $1 ###"
	if [[ $1 == 'DEFAULT'  ]] ; then
		wrapper=""
	else
		wrapper="ip netns exec $1"
	fi
	echo "### LINKS: $1 ###"
	$wrapper ip addr
	echo "### IPTABLES: $1 ###"
	#$wrapper iptables -S | grep -v '\(^-P INPUT ACCEPT$\)\|\(khjgdkfgaskdf\)'
	$wrapper iptables -S | grep -v '\(^-P INPUT ACCEPT$\)\|\(^-P FORWARD ACCEPT$\)\|\(^-P OUTPUT ACCEPT$\)'

	# $wrapper iptables-save |grep -v '\(virbr0\)\|\(^:\)\|\(^#\)\|\(^COMMIT$\)'
	echo "###"
	echo
}

echo "### OVSWITCH ###"
ovs-vsctl show
state_report "DEFAULT"
for ns in `ip netns` ; do state_report $ns ; done
